Commit 01
MarinaVolk/java-explore-with-me pull request #5
Opened 2023-10-31 19:51 UTC by MarinaVolk

feature_comments

2023-11-01 10:39 UTC, tomattman requested changes
Привет, надо еще поработать над структурой базы данных, а после ее переделки многое придётся переработать в сервисы и все остальное

2023-11-01 10:39 UTC, tomattman commented on README.md
> +https://github.com/MarinaVolk/java-explore-with-me/pull/5
Стоило бы добавить больше информации о самом проекте в ридми файл

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/comments_models/Comment.java
> +    private Long eventId;
при использовании JPA обычно используются не числовые поля с id а поля обьекты, и аннотации @ManyToOne @OneToMany @ManyToMany

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/comments_models/Comment.java
> +    @JoinTable(name = "responses_comment",
Кажется не очень соотносится тип связи с объектной моделью, только если один комментарий будет ответом сразу на несколько других комментариев, но это тяжело представить

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/comments_models/CommentShortResponseDto.java
> +    private List<Comment> responses;
почему Dto содержит в себе обьекты которые не являются Dto 
скорее всего тут стоит использовать CommentShortResponseDto

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    private final CommentService service;
лучше давать сразу полные имена, так сразу и читабельнее и понятнее, и потом чуть что редактировать не прийдется

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public CommentFullResponseDto getCommentByAdmin(@PathVariable(name = "commentId") @Min(1) Long commentId) {
не очень уместная валидация на id
идентификатор может быть как 0 так и отрицательным значением, особенно это удобно если есть какие то предустановленные значения, например предустановленные могут иметь отрицательные значения, а пользовательские - автоматически генерируемые

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public CommentFullResponseDto updateCommentByAdmin(@RequestBody @Valid CommentRequestDto request,
аналогично

2023-11-01 10:39 UTC, tomattman commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public void deleteCommentByAdmin(@PathVariable(name = "commentId") @Min(1) Long commentId) {
и аналогично

2023-11-01 18:28 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/comments_models/Comment.java
> +    private Long eventId;
Переделано на объекты Event и User.

2023-11-01 18:29 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/comments_models/Comment.java
> +    @JoinTable(name = "responses_comment",
Переделано.

2023-11-01 18:29 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/comments_models/CommentShortResponseDto.java
> +    private List<Comment> responses;
Скорректировано.

2023-11-01 18:29 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    private final CommentService service;
Скорректировано.

2023-11-01 18:30 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public CommentFullResponseDto getCommentByAdmin(@PathVariable(name = "commentId") @Min(1) Long commentId) {
Скорректировано.

2023-11-01 18:30 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public void deleteCommentByAdmin(@PathVariable(name = "commentId") @Min(1) Long commentId) {
Скорректировано.

2023-11-01 18:32 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/AdminCommentController.java
> +    public AdminCommentController(CommentService service) {
Переделано.

2023-11-01 18:33 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/CommentServiceImpl.java
> +    public CommentServiceImpl(CommentRepository comRep, UserRepository userRep, EventRepository eventRep) {
Переделано на аннотацию.

2023-11-01 18:33 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/CommentServiceImpl.java
> +        /*if (!event.getState().equals(EventState.PUBLISHED)) {
Удалено.

2023-11-01 18:34 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/CommentServiceImpl.java
> +    private Comment commentValidate(Long userId, Long commentId) {
Удалено.

2023-11-01 18:34 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/CommentServiceImpl.java
> +        final Comment comment = commentValidate(userId, commentId);
Скорректировано. Метод избыточен.

2023-11-01 18:35 UTC, MarinaVolk commented on main-service/src/main/java/ru/practicum/comments/logic/CommentServiceImpl.java
> +        final Comment comment = commentValidate(userId, commentId);
Скорректировано.

2023-11-01 18:36 UTC, MarinaVolk commented on main-service/src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS responses_comment (
Скорректировано. Поле private Boolean isResponse показывает response это или нет. Поэтому излишняя таблица исключена.

2023-11-02 08:45 UTC, tomattman requested changes
Привет, осталось еще одна небольшая нестыковка

2023-11-02 08:45 UTC, tomattman commented on main-service/src/main/resources/schema.sql
> +    is_response BOOLEAN,
Остался один непонятный момент, если это ответ на комментарий, так как понять, на какой комментарий это ответ
лучше сделать поле parrent_comment_id и по нему понимать ответ это или нет, если id == null то это не ответ, если  id != null то это ответ на комментарий,  и id отвечает за то, на какой коментарий этот id

2023-11-02 09:30 UTC, MarinaVolk commented on main-service/src/main/resources/schema.sql
> +    is_response BOOLEAN,
Привет. Дополнила полем parrent_comment_id и внесла сопутствующие правки.

2023-11-02 10:57 UTC, tomattman approved these changes
Принято. хотя можно было родительский комментарий тоже сделать как объект, а не как id

2023-11-02 11:00 UTC, merged